backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

# Publish mode for editorial workflow (optional)
publish_mode: simple

# Media folder where uploads will be stored
media_folder: "src/.vuepress/public/images/uploads"
public_folder: "/images/uploads"

# Collections define the structure for content types
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        file: "src/index.md"
        fields:
          - {label: "Layout", name: "home", widget: "hidden", default: true}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
          - {label: "Background Image (Light)", name: "bgImage", widget: "image", required: false}
          - {label: "Background Image (Dark)", name: "bgImageDark", widget: "image", required: false}
          - {label: "Hero Text", name: "heroText", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "About Title", name: "aboutTitle", widget: string}
          - {label: "About Content", name: "body", widget: "markdown"}
          - {label: Max Articles Length, name: articlesLength, widget: number}
          - {label: Funding Title, name: fundingTitle, widget: string}
          - label: Funding Images
            name: fundingImages
            widget: list 
            required: false
            fields:
              - {label: Imagei, name: src, widget: image}
              - {label: Height (px), name: height, widget: number, default: 150}
              - {label: Width (px), name: width, widget: number, default: 150}
          - {label: "Footer Copyright Status", name: "copyright", widget: "boolean", default: false}
          - {label: "Footer Content", name: "footer", widget: "markdown", required: false}
      
      - name: about
        label: About
        file: "src/about/index.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Content, name: body, widget: markdown}
      
      - name: "publications"
        label: "Publications"
        file: "src/publications/index.md"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: "Content", name: "body", widget: "markdown", required: true}

      - name: "contact"
        label: Contact Page (Only Body, info taken from Info/Contact)
        file: src/contact/index.md
        fields:
          - {label: Content, name: body, widget: markdown}

  - name: "info"
    label: "Info"
    files: 
      - name: contact
        label: Contact Info
        file: src/data/contact/contact.json
        extension: json
        fields:
          - {label: Contact Phone, name: contactPhone, widget: string, required: false}
          - {label: Contact Email, name: contactEmail, widget: string, required: true}
          - {label: Contact Person Photo, name: contactPersonPhoto, widget: image, required: false}
          - {label: Contact Person Name, name: contactPersonName, widget: string, required: false} 
          - {label: Contact Person Position, name: contactPersonPosition, widget: string, required: false}
          - {label: Institution Logo, name: institutionLogo, widget: image, required: false}
          - {label: Institution Name, name: institutionName, widget: string, required: false}
          - {label: Institution Photo, name: institutionPhoto, widget: image, required: false}
          - {label: Institution Address, name: institutionAddress, widget: string, required: false}

  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    filter:
      field: article
      value: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Is Article?", "name": "article", widget: "hidden", default: true}
      
  - name: "members"
    label: "Team Members"
    folder: "src/data/members"
    extension: "json"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Photo", name: "image", widget: "image", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Order", name: "order", widget: "number", default: 10, required: false, hint: "Lower numbers appear first"}

